# Generated by Django 3.2.5 on 2021-11-27 19:45

import arduinoPolls.randomNames
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(default=arduinoPolls.randomNames.makeRandomName, max_length=50)),
                ('Creado', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('Modificado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
