# Generated by Django 3.2.5 on 2021-11-27 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduinoPolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturas',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='arduinoPolls.arduino')),
                ('Tiempo_lectura', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('Lectura_1', models.FloatField(null=True)),
                ('Lectura_2', models.FloatField(null=True)),
                ('Lectura_3', models.FloatField(null=True)),
            ],
        ),
    ]
