# Generated by Django 3.2.5 on 2021-11-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduinoPolls', '0003_auto_20211127_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturas',
        ),
    ]
