# Generated by Django 3.2.5 on 2021-11-27 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduinoPolls', '0004_delete_lecturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tiempo_lectura', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('Lectura_1', models.FloatField(help_text='CO2', null=True)),
                ('Lectura_2', models.FloatField(help_text='CO', null=True)),
                ('Lectura_3', models.FloatField(null=True)),
                ('Arduino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduinoPolls.arduino')),
            ],
        ),
    ]
